compatibility_date = "2025-03-03"
main = "index.ts"
name = "northwind-worker"
compatibility_flags = ["nodejs_compat", "enable_d1_with_sessions_api"]
route = "api.northwind.d1sql.com/*"

[placement]
mode = "off"

[observability]
enabled = true
head_sampling_rate = 1

[[d1_databases]]
binding = "DB"
database_name = "northwind"
database_id = "d5b1d127-1d3f-467e-953b-cbc69f0a9e06"
